# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_access_row.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61pp_access_row.proto\"\xa1\x01\n\x0e\x43ustomerRecord\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x03(\t\x12\x11\n\tauthLevel\x18\x03 \x03(\x05\x12\x13\n\x0bgeolocation\x18\x04 \x03(\t\x12\x11\n\tuserAgent\x18\x05 \x03(\t\x12\x0f\n\x07\x61ppflag\x18\x06 \x03(\t\x12\n\n\x02ip\x18\x07 \x03(\t\x12\x14\n\x0chitDictLevel\x18\x08 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_access_row_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMERRECORD._serialized_start=25
  _CUSTOMERRECORD._serialized_end=186
# @@protoc_insertion_point(module_scope)
