# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grand_block_row.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15grand_block_row.proto\"\xce\x01\n\rgrantBlockMsg\x12\x0f\n\x07userkey\x18\x01 \x01(\t\x12)\n\x03rec\x18\x02 \x03(\x0b\x32\x1c.grantBlockMsg.grantBlockRec\x12\n\n\x02\x64t\x18\x03 \x01(\t\x1au\n\rgrantBlockRec\x12\x0f\n\x07geoCity\x18\x01 \x01(\t\x12\x12\n\ngeoCountry\x18\x02 \x01(\t\x12\x11\n\tgeoRegion\x18\x03 \x01(\t\x12\n\n\x02ip\x18\x04 \x01(\t\x12\x0e\n\x06target\x18\x05 \x01(\t\x12\x10\n\x08username\x18\x06 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grand_block_row_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRANTBLOCKMSG._serialized_start=26
  _GRANTBLOCKMSG._serialized_end=232
  _GRANTBLOCKMSG_GRANTBLOCKREC._serialized_start=115
  _GRANTBLOCKMSG_GRANTBLOCKREC._serialized_end=232
# @@protoc_insertion_point(module_scope)
