# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tunnelblock_row.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tunnelblock_row.proto\"\x9a\x01\n\x0etunnelBlockMsg\x12\x0f\n\x07userkey\x18\x01 \x01(\t\x12+\n\x03rec\x18\x02 \x03(\x0b\x32\x1e.tunnelBlockMsg.tunnelBlockRec\x12\n\n\x02\x64t\x18\x03 \x01(\t\x1a>\n\x0etunnelBlockRec\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tunnelblock_row_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TUNNELBLOCKMSG._serialized_start=26
  _TUNNELBLOCKMSG._serialized_end=180
  _TUNNELBLOCKMSG_TUNNELBLOCKREC._serialized_start=118
  _TUNNELBLOCKMSG_TUNNELBLOCKREC._serialized_end=180
# @@protoc_insertion_point(module_scope)
